name: eeg_pipeline
version: "1.0.0"
config-version: 2

profile: eeg_pipeline

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  eeg_pipeline:
    staging:
      +materialized: view  
      # staging models are views for fast iteration and transformation logic testing
    marts:
      +materialized: table # marts are tables for serving layer, we want them to be fast for querying, so we materialize them as tables
