from pyspark.sql import SparkSession
from pyspark.sql.functions import (
    from_json,
    col,
    when,
    abs,
    min,
    max,
    sum,
    mean,
    stddev,
    to_timestamp,
    to_date,
    window,
)
from pyspark.sql.types import (
    StructType,
    StructField,
    StringType,
    DoubleType,
    IntegerType,
    LongType,
)

spark = (
    SparkSession.builder.appName("eeg-stream-processor")
    .config(
        "spark.jars.packages",  # java archives is a bundled library file. Spark is built on top of JVM, so need these jars.
        "org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0,"
        "io.delta:delta-spark_2.12:3.2.0",
    )
    .config(
        "spark.sql.extensions", "io.delta.sql.DeltaSparkSessionExtension"
    )  # delta lake extension
    .config(
        "spark.sql.catalog.spark_catalog",
        "org.apache.spark.sql.delta.catalog.DeltaCatalog",
    )  # table metadata for delta lake
    .getOrCreate()
)

spark.sparkContext.setLogLevel("ERROR")

# reading from kafka topic eeg-raw
eeg_raw_df = (
    spark.readStream.format("kafka")
    .option(
        "kafka.bootstrap.servers", "localhost:29092"
    )  # connect to EXTERNAL listener
    .option("subscribe", "eeg-raw")  # subscribe tells spark which topic to read from
    .option("startingOffsets", "earliest")
    .option("failOnDataLoss", "false")
    .load()
)

# schema to match the JSON message
schema = StructType(
    [
        StructField("patient_id", StringType(), True),
        StructField("timestamp_ms", LongType(), True),
        StructField("channel", StringType(), True),
        StructField("voltage", DoubleType(), True),
        StructField("sample_index", IntegerType(), True),
    ]
)

# column value from kafka is in bytes, so cast to string then parse the JSON using the schema
eeg_parsed_df = eeg_raw_df.select(
    from_json(col=col("value").cast("string"), schema=schema).alias("data")
).select(
    "data.*"
)  # this selects all the fields from the parsed JSON and flattens the dataframe

# withColumn creates a new column event_time that is just in seconds unit
eeg_parsed_df = eeg_parsed_df.withColumn(
    "event_time", (col("timestamp_ms") / 1000).cast("timestamp")
)

# a little confusing here, but we are extracting the mean, stddev, min, max microvolt values per channel, per patient, in a tumbling window of 5 seconds.
eeg_analytic_df = (
    eeg_parsed_df
    .withWatermark(
        "event_time", "3 seconds"
    )  # watermark is the threshold for how late data can arrive, so irl, this 10s can be like the network delay in the hospital network
    .groupBy(
        window("event_time", "5 seconds"), "patient_id", "channel"
    )  # window is 5s, which means we are grouping data in 5s intervals
    .agg(
        mean("voltage").alias("mean_uv"),
        stddev("voltage").alias("stddev_uv"),
        min("voltage").alias("min_uv"),
        max("voltage").alias("max_uv"),
        sum(
            when(abs(col("voltage")) > 0.0001, 1).otherwise(0)
        ).alias(  # we take the absolute value and check if its > 100microv, if yes then its a spike.
            "spike_count"
        ),
    )
)

# In a 5s winddow, if there are more than 10 spikes then we flag it as spike threshold, or if the stddev is greater than 100mv then we also flag it as spike threshold, otherwise its None.
# This is a very simple rule based alerting system, just for demonstration purposes, i would use ML for this in the future.
eeg_analytic_df = eeg_analytic_df.withColumn(
    "alert_reason",
    when(col("spike_count") > 10, "spike_threshold")
    .when(col("stddev_uv") > 0.00001, "high_variance")
    .otherwise(None),
)


# user defined function that has the following logic below. batch_id is not used but required for foreachBatch below
def process_batch(batch_df, batch_id):
    # print(f"Processing batch {batch_id} with {batch_df.count()} records")

    # extract window start and end times
    batch_df = (
        batch_df.withColumn("window_start", col("window.start"))
        .withColumn("window_end", col("window.end"))
        .withColumn("event_date", to_date(col("window.start")))
        .drop("window")
    )

    # writes all rows to eeg_features
    (
        batch_df.write.format("delta")
        .mode("append")
        .partitionBy(
            "patient_id", "event_date"
        )  # saves data in folders of patient_id=xxx/event_date=xxx for efficient querying later
        .save("./data/delta/eeg_features")
    )

    # filters where alert reason is not null, then send to eeg_alerts
    alerts_df = batch_df.filter(col("alert_reason").isNotNull())
    (
        alerts_df.write.format("delta")
        .mode("append")
        .partitionBy("patient_id", "event_date")
        .save("./data/delta/eeg_alerts")
    )


# spark holds on to process_batch and calls it on our behalf
# apply process_batch to each batch of data in the stream, batch_id is generated by spark
eeg_analytic_df.writeStream.foreachBatch(process_batch).option(
    "checkpointLocation", "./data/checkpoints/eeg_stream"
).start().awaitTermination()


# rm -rf ./data/checkpoints/eeg_stream # if u wanna reset the checkpoints and reprocess the stream from the beginning
# rm -rf ./data/delta/eeg_features ./data/delta/eeg_alerts # if u wanna reset the delta lake tables
